### ISSUE TITLE
Invalid XML-RPC message

### ISSUE THREAD

**Issue by Skinner927** [mjpizz/node-virtualenv#6]
I'm not able to run the post install. I'm using node-virtualenv 0.3.0, and just updated virtualenv via pip. 

This is the error I'm getting: `Error: unable to retrieve version information for virtualenv`

I appended the `err` object that's part of the error handler to see what that said and here it is: `Error: Invalid XML-RPC message`.

From googling around it seems this might be a http vs https issue, but I don't know for certain. It seems you're using pypi to determine virtualenv version. On this line: https://github.com/lukaszb/pypi/blob/master/src/pypi/client.coffee#L3 we can see it's hitting `http://pypi.python.org/pypi`. Curling this returns a 301 redirect to https which I believe is failing. If you try to switch the url to https there's an error about not supporting https.

Maybe this is an issue that should be brought up with pypi, not sure. Any ideas?

**Comment by Skinner927** [comment]
Looks like this PR for pypi does the trick: https://github.com/lukaszb/pypi/pull/3

**Comment by mjpizz** [comment]
ah great - thanks Dennis for pointing out the pypi PR. Assuming that update is published to npm, you should be able to reinstall node-virtualenv to get the latest pypi. I'm going to close this issue as resolved.
